kraken:
 general: "--output - --gzip-compressed --paired"
 db: "/home/vdputten/kraken_db_nohuman"

shovill:
 minlen: "500"
 ram: "64"
 depth: "100"
 assembler: "spades"
 tmpdir: "$TMPDIR"

timestamp: "1950.01.01_00.00.00"
