# Kraken config: only output report (not raw output), input is paired, gzipped data
# Location of kraken2 database is provided
kraken:
 general: "--output - --gzip-compressed --paired"
 db: "/home/nvsorge/kraken2_database"

# Shovill config for SLURM nodes (requires >64 Gb!)
shovill:
 minlen: "500"
 ram: "64"
 depth: "100"
 assembler: "spades"
 tmpdir: "$TMPDIR"

pubmlst:
 ecoli_mlst_scheme: "https://rest.pubmlst.org/db/pubmlst_escherichia_seqdef/schemes/1/sequence"
 ecoli_mlst_loci: "adk,fumC,gyrB,icd,mdh,purA,recA"
 ecoli_cgmlst_scheme: "https://rest.pubmlst.org/db/pubmlst_escherichia_seqdef/schemes/6/sequence"
 nmen_mlst_scheme: "https://rest.pubmlst.org/db/pubmlst_neisseria_seqdef/schemes/1/sequence"
 nmen_mlst_loci: "abcZ,adk,aroE,fumC,gdh,pdhC,pgm"
 nmen_vaccine_antigen_scheme: "https://rest.pubmlst.org/db/pubmlst_neisseria_seqdef/schemes/77/sequence"
 nmen_cgmlst_scheme: "https://rest.pubmlst.org/db/pubmlst_neisseria_seqdef/schemes/47/sequence"
 spyo_mlst_scheme: "https://rest.pubmlst.org/db/pubmlst_spyogenes_seqdef/schemes/1/sequence"
 spyo_mlst_loci: "gki,gtr,murI,mutS,recP,xpt,yqiL"

ectyper:
 general: "--sequence"

abricate:
 fimH_db: "fimtyper_db"
 fimH_datadir: "workflow/db"
 VFDB_db: "vfdb"
 minid: 90
 mincov: 70

snippy:
 general: "--force --cleanup"

mash:
 threshold: 0.005

ska:
 proportion: 0.1

convert_snps_to_network:
 threshold: 25

# Default timestamp to prevent errors
timestamp: "1950.01.01_00.00.00"
